project:
  type: website

website:
  title: "Shwetank Kumar"
  navbar:
    right:
      - icon: github
        href: https://github.com/shwetank-kumar
      - icon: twitter
        href: https://twitter.com/shwetankumar
      - icon: linkedin
        href: https://www.linkedin.com/in/shwetankkumar
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    # toc-title: Table of contents
    # toc-location: left
    # page-layout: article
    # toc-expand: false





