project:
  type: website

website:
  title: "Shwetank Kumar"
  site-url: "https://shwetank-kumar.github.io/"
  description: "Shwetank Kumar's personal website"
  navbar:
    right:
      - text: "About"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Eggheadery"
        href: favorite-eggheads.qmd
      - icon: github
        href: https://github.com/shwetank-kumar
      - icon: twitter
        href: https://twitter.com/shwetankumar
      - icon: linkedin
        href: https://www.linkedin.com/in/shwetankkumar
      - icon: rss
        href: index.xml
  google-analytics: "G-WYRPY1S3G7"
  search: false
  page-navigation: false
  sidebar: false

format:
  html:
    toc: false
    theme: cosmo
    css: styles.css
    page-layout: full  # Add this line
    grid:
      sidebar-width: 0px  # Add this line
      body-width: 1200px  # Add this line
    mainfont: "Helvetica, Arial, sans-serif"  # Optional: for consistent font

# listing:
#   contents: posts
#   sort: "date desc"
#   type: default
#   categories: false
#   sort-ui: false
#   filter-ui: false
#   fields: [date, title, reading-time, description]
#   feed: true