project:
  type: website

website:
  title: "Shwetank Kumar"
  navbar:
    right:
      - icon: github
        href: https://github.com/shwetank-kumar
      - icon: twitter
        href: https://twitter.com/shwetankumar
      - icon: linkedin
        href: https://www.linkedin.com/in/shwetankkumar
  search: false
  sidebar: false  # This will disable any sidebar, including TOC

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full  # This ensures a full-width layout without sidebars