project:
  type: website

website:
  title: "Shwetank Kumar"
  site-url: "https://shwetank-kumar.github.io/"
  description: "Shwetank Kumar's personal website"
  navbar:
    right:
      - text: "About"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Eggheadery"
        href: favorite-eggheads.qmd
      - icon: github
        href: https://github.com/shwetank-kumar
      - icon: twitter
        href: https://twitter.com/shwetankumar
      - icon: linkedin
        href: https://www.linkedin.com/in/shwetankkumar
      - icon: rss
        href: index.xml
  google-analytics: "G-WYRPY1S3G7"
  search: false

format:
  html:
    toc: false
    theme: cosmo
    css: styles.css
    page-layout: custom
    sidebar:
      - id: subscribe
        title: "Subscribe"
        style: "floating"
        collapse-level: 2
        align: right
        contents: 
          - subscribe.qmd
    mainfont: "Helvetica, Arial, sans-serif"  # Optional: for consistent font