project:
  type: website

website:
  title: "Shwetank Kumar"
  navbar:
    right:
      - text: "Blog"
        href: blog.qmd
      - text: "About"
        href: index.qmd
      - icon: github
        href: https://github.com/shwetank-kumar
      - icon: twitter
        href: https://twitter.com/shwetankumar
      - icon: linkedin
        href: https://www.linkedin.com/in/shwetankkumar
  search: false
  sidebar: false

format:
  html:
    toc: false
    theme: cosmo
    css: styles.css
    # page-layout: full