project:
  type: website

website:
  title: "Shwetank Kumar"
  site-url: "https://shwetank-kumar.github.io/"
  description: "Shwetank Kumar's personal website"
  navbar:
    right:
      - text: "About"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Eggheadery"
        href: favorite-eggheads.qmd
      - icon: github
        href: https://github.com/shwetank-kumar
      - icon: twitter
        href: https://twitter.com/shwetankumar
      - icon: linkedin
        href: https://www.linkedin.com/in/shwetankkumar
      - icon: rss
        href: index.xml
  search: false
  margin-header: subscribe.html

format:
  html:
    toc: false
    theme: cosmo
    css: styles.css