---
title: false
sidebar: subscribe
format:
  html:
    css: styles.css
    toc: false
twitter-card:
  card-style: summary
  creator: "@shwetankumar"
---

<div class="about-content">

<div class="about-section">
## Personal info in a nutshell
I'm a physicist, engineering exec, investor. Here's my story:

* Born and raised in NCR, India. Delhi native, I live in SF.
* Got hooked on science early, did my B.Tech in EE from IIT, PhD in Applied Physics from Caltech.
* Learned business by working at startups for 10+ years and getting MBA at Wharton.
* I founded a bootstrapped company to help data teams optimize their Snowflake spend.
* I enjoy building stuff for internet and physical systems using data and AI games.
</div>

<div class="about-section">
## Some things I've done
* Built AI systems that crunch petabytes of data across image, text, and tabular formats.
* Scaled these systems to serve millions of customers simultaneously [1](achieve.com), [2](turo.com).
* [Created systems](https://orbitalinsight.com/geospatial-technology) that use neural networks to analyze satellite imagery at planet scale.
* Led teams of 120+ [brilliant minds](https://www.fastcompany.com/3067492/why-orbital-insight-is-one-of-the-most-innovative-companies-of-201) in data science, engineering, and analytics.
</div>

<div class="about-section">
## Tech I love working with:
* PyTorch, Hugging Face, Langchain, Pydantic
* GCP, Snowflake, Bigquery
* Anything that pushes the boundaries of what's possible with data 
</div>

<div class="about-section">
## Investing:
* My current areas of interest are: AI, infrastructure, open source, physical systems / frontier tech.
* Some companies I have invested in - Comet, Startree, Inference, Nimble, Turnstile, Dandelion...
* I am a founding member and part of the steering committee at Invest in Data where I co-invest with a group of ~50 other Data execs.
* We vet and invest on a quarterly cadence. If you have an exciting AI project or a game-changing startup idea? Let's talk: shwetank.kumar@gmail.com.
</div>

<div class="about-section">
## Where you can find me:
* Writing about AI musings, tech & leadership, and data science on this blog
* Sharing insights on [LinkedIn](https://www.linkedin.com/in/shwetankkumar/)
* Tinkering with code on [GitHub](https://github.com/shwetank-kumar)
* Speaking on panels about the future of AI and data
</div>

</div>

<!-- ---
# title: False
sidebar: subscribe
format:
  html:
    css: styles.css
    toc: false
twitter-card:
  card-style: summary
  creator: "@shwetankumar"
---

## Personal info in a nutshell
I'm a physicist, engineering exec, investor. Here's my story:

* Born and raised in NCR, India. Delhi native, I live in SF.
* Got hooked on science early, did my B.Tech in EE from IIT, PhD in Applied Physics from Caltech.
* Learned business by working at startups for 10+ years and getting MBA at Wharton.
* I founded a bootstrapped company to help data teams optimize their Snowflake spend.
* I enjoy building stuff for internet and physical systems using data and AI games.

## Some things I've done
* Built AI systems that crunch petabytes of data across image, text, and tabular formats.
* Scaled these systems to serve millions of customers simultaneously [1](achieve.com), [2](turo.com).
* [Created systems](https://orbitalinsight.com/geospatial-technology) that use neural networks to analyze satellite imagery at planet scale.
* Led teams of 120+ [brilliant minds](https://www.fastcompany.com/3067492/why-orbital-insight-is-one-of-the-most-innovative-companies-of-201) in data science, engineering, and analytics.

## Tech I love working with:
* PyTorch, Hugging Face, Langchain, Pydantic
* GCP, Snowflake, Bigquery
* Anything that pushes the boundaries of what's possible with data 

## Investing:
* My current areas of interest are: AI, infrastructure, open source, physical systems / frontier tech.
* Some companies I have invested in - Comet, Startree, Inference, Nimble, Turnstile, Dandelion...
* I am a founding member and part of the steering committee at Invest in Data where I co-invest with a group of ~50 other Data execs.
* We vet and invest on a quarterly cadence. If you have an exciting AI project or a game-changing startup idea? Let's talk: shwetank.kumar@gmail.com.

## Where you can find me:
* Writing about AI musings, tech & leadership, and data science on this blog
* Sharing insights on [LinkedIn](https://www.linkedin.com/in/shwetankkumar/)
* Tinkering with code on [GitHub](https://github.com/shwetank-kumar)
* Speaking on panels about the future of AI and data -->
